// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One address (public string + asset symbol) under a holding. Both are
 * shown to the user — the asset symbol is the primary label, the address
 * is displayed truncated with the full string on hover/copy. Never a
 * private key or seed phrase; there is no column anywhere for those.
 */
export type AddressDto = { id: number, asset: string, address: string, label: string | null, };
