// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of committing an import batch.
 */
export type CommitSummaryDto = { ledger_entries_committed: number, cash_activity_entries_committed: number, transfers_auto_resolved: number, };
