// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A holding, as offered to a picker/dropdown. `display_name` is a computed
 * convenience label (the venue's name alone for a single-holding venue,
 * "Venue — Holding" otherwise) — not the raw `holdings.name` column.
 */
export type Holding = { id: number, display_name: string, };
