// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressDto } from "./AddressDto";

/**
 * A holding, with its addresses, as shown in the read-only venue hierarchy
 * view.
 */
export type HoldingHierarchyDto = { holding_id: number, holding_name: string, entity_name: string, account_identifier: string | null, is_default_holding: boolean, addresses: Array<AddressDto>, };
