// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of parsing + staging one CSV file: what a reconciliation review
 * screen needs before anything is written to the ledger.
 */
export type ImportPreviewDto = { batch_id: number, total_rows: number, new_count: number, matched_existing_count: number, near_duplicate_count: number, pending_transfer_count: number, cash_activity_count: number, parse_errors: Array<string>, };
