// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the immutable ledger, as read back for the grid.
 */
export type LedgerEntryDto = { id: number, holding_id: number, holding_name: string, entry_type: string, asset: string, qty: string, cost_basis_per_unit: string | null, proceeds_total: string | null, trade_id: string | null, transfer_id: string | null, event_at: string, created_at: string, };
