// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lot as derived from the ledger, for the "current holdings" grid. With
 * BUY-only entries this is a 1:1 projection of each entry (nothing has
 * consumed it yet) — but it's computed fresh from the ledger every time,
 * not stored, so the recompute-from-ledger principle holds even now.
 */
export type LotDto = { lot_id: number, holding_id: number, holding_name: string, asset: string, qty_remaining: string, cost_basis_per_unit: string, acquired_at: string, };
