// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A disposal: SELL for cash, or the taxable ones that aren't a SELL
 * (GIFT_OUT, FEE_BURN — proceeds are 0 for both, but they're still recorded
 * as disposals so basis leaves the ledger correctly).
 */
export type NewDisposalEntry = { holding_id: number, asset: string, qty: string, proceeds_total: string, 
/**
 * Date of the sale/gift/burn, e.g. "2026-01-15".
 */
event_at: string, };
