// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * De minimis unsolicited incoming (dust). Always $0 cost basis by
 * convention — not user-entered — and always flagged for CPA review.
 */
export type NewDustInEntry = { holding_id: number, asset: string, qty: string, event_at: string, };
