// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Income (staking reward, airdrop, etc.): an acquisition at fair-market
 * value on the day received.
 */
export type NewIncomeEntry = { holding_id: number, asset: string, qty: string, cost_basis_per_unit: string, event_at: string, };
