// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the BUY entry form submits: an acquisition of `qty` units of `asset`
 * in `holding_id`, at `cost_basis_per_unit` each.
 */
export type NewLedgerEntry = { holding_id: number, asset: string, qty: string, cost_basis_per_unit: string, 
/**
 * Date the asset was acquired, e.g. "2026-01-15".
 */
acquired_at: string, };
