// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transfer between two of the end user's own holdings — non-taxable. Basis and
 * acquisition date travel with the coins; both legs share a `transfer_id`.
 */
export type NewTransferEntry = { from_holding_id: number, to_holding_id: number, asset: string, qty: string, event_at: string, };
