// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A crypto-to-crypto trade: one asset disposed, another acquired, both legs
 * at the same holding and the same moment, linked by a shared `trade_id`.
 * `fmv_total` is the fair-market-value of what came back — it becomes both
 * the TRADE_OUT's proceeds and the TRADE_IN's total cost basis.
 */
export type NewTradeEntry = { holding_id: number, asset_out: string, qty_out: string, asset_in: string, qty_in: string, fmv_total: string, event_at: string, };
