// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A review flag surfaced alongside the ledger/lots view: something the app
 * deliberately didn't decide for the user (a cross-entity transfer, a
 * FEE_BURN whose tax treatment is unsettled, a DUST_IN parcel) and instead
 * hands to the CPA.
 */
export type ReviewFlagDto = { entry_id: number, reason: string, };
