// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One staged row, as shown in the import review grids.
 */
export type StagingRowDto = { id: number, import_batch_id: number, target_table: string, entry_type: string | null, asset: string | null, qty: string | null, cost_basis_per_unit: string | null, proceeds_total: string | null, event_at: string | null, classification: string, decision: string | null, transfer_leg: string | null, };
