// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HoldingHierarchyDto } from "./HoldingHierarchyDto";

/**
 * One venue with all of its holdings, for the read-only Venue > Holding >
 * Address tree (`VenueHierarchy.tsx`). No CRUD UI yet — the real inventory
 * is entered by hand in `seed.rs` until a management screen exists.
 */
export type VenueHierarchyDto = { venue_id: number, venue_name: string, venue_type: string, holdings: Array<HoldingHierarchyDto>, };
