// Thin wrapper around invoke() so the rest of the app never spells a command
// name or a bare invoke<T> call directly. Types come from src/bindings, which
// is generated by `cargo test` in src-tauri/ (see ts-rs derives in models.rs)
// — if a Rust DTO field changes, this stays in sync automatically as long as
// you re-run the tests.
import { invoke } from "@tauri-apps/api/core";
import type { Holding } from "./bindings/Holding";
import type { NewLedgerEntry } from "./bindings/NewLedgerEntry";
import type { NewDisposalEntry } from "./bindings/NewDisposalEntry";
import type { NewTradeEntry } from "./bindings/NewTradeEntry";
import type { NewTransferEntry } from "./bindings/NewTransferEntry";
import type { NewIncomeEntry } from "./bindings/NewIncomeEntry";
import type { NewDustInEntry } from "./bindings/NewDustInEntry";
import type { LedgerEntryDto } from "./bindings/LedgerEntryDto";
import type { LotDto } from "./bindings/LotDto";
import type { ReviewFlagDto } from "./bindings/ReviewFlagDto";
import type { VenueHierarchyDto } from "./bindings/VenueHierarchyDto";
import type { ImportPreviewDto } from "./bindings/ImportPreviewDto";
import type { StagingRowDto } from "./bindings/StagingRowDto";
import type { CommitSummaryDto } from "./bindings/CommitSummaryDto";

export const api = {
  listHoldings: () => invoke<Holding[]>("list_holdings"),
  addLedgerEntry: (entry: NewLedgerEntry) =>
    invoke<LedgerEntryDto>("add_ledger_entry", { entry }),
  addSellEntry: (entry: NewDisposalEntry) =>
    invoke<LedgerEntryDto>("add_sell_entry", { entry }),
  addGiftOutEntry: (entry: NewDisposalEntry) =>
    invoke<LedgerEntryDto>("add_gift_out_entry", { entry }),
  addFeeBurnEntry: (entry: NewDisposalEntry) =>
    invoke<LedgerEntryDto>("add_fee_burn_entry", { entry }),
  addIncomeEntry: (entry: NewIncomeEntry) =>
    invoke<LedgerEntryDto>("add_income_entry", { entry }),
  addDustInEntry: (entry: NewDustInEntry) =>
    invoke<LedgerEntryDto>("add_dust_in_entry", { entry }),
  addTradeEntry: (entry: NewTradeEntry) =>
    invoke<LedgerEntryDto[]>("add_trade_entry", { entry }),
  addTransferEntry: (entry: NewTransferEntry) =>
    invoke<LedgerEntryDto[]>("add_transfer_entry", { entry }),
  listLedgerEntries: () => invoke<LedgerEntryDto[]>("list_ledger_entries"),
  listLots: () => invoke<LotDto[]>("list_lots"),
  listReviewFlags: () => invoke<ReviewFlagDto[]>("list_review_flags"),
  listVenueHierarchy: () => invoke<VenueHierarchyDto[]>("list_venue_hierarchy"),
  importCsvPreview: (args: { filePath: string; venueId: number; holdingId: number; format: string }) =>
    invoke<ImportPreviewDto>("import_csv_preview", {
      filePath: args.filePath,
      venueId: args.venueId,
      holdingId: args.holdingId,
      format: args.format,
    }),
  listStagingRows: (batchId: number) => invoke<StagingRowDto[]>("list_staging_rows", { batchId }),
  resolveStagingRow: (rowId: number, decision: string) =>
    invoke<void>("resolve_staging_row", { rowId, decision }),
  importCsvCommit: (batchId: number) => invoke<CommitSummaryDto>("import_csv_commit", { batchId }),
  listPendingTransfers: () => invoke<StagingRowDto[]>("list_pending_transfers"),
  resolvePendingTransferPair: (outStagingId: number, inStagingId: number) =>
    invoke<void>("resolve_pending_transfer_pair", { outStagingId, inStagingId }),
};

export type {
  Holding,
  NewLedgerEntry,
  NewDisposalEntry,
  NewTradeEntry,
  NewTransferEntry,
  NewIncomeEntry,
  NewDustInEntry,
  LedgerEntryDto,
  LotDto,
  ReviewFlagDto,
  VenueHierarchyDto,
  ImportPreviewDto,
  StagingRowDto,
  CommitSummaryDto,
};
